### PR TITLE
update packages move to .net core and expecto and run tests against dynamodb local

### PR DESCRIPTION
**Pull request by AviAvni**
@eiriktsarpalis @forki  on my machine this build without errors all tests pass with the dynamodb local

### CODE REVIEW

**Comment by AviAvni** [comment]
the windows build pass the linux build fail because I changed the test project to net46 I think

**Comment by AviAvni** [comment]
@eiriktsarpalis @forki  so now I moved to .net core there is a problem installing mono can we avoid it?

**Comment by eiriktsarpalis** [comment]
I think xunit doesn't support hosting mono test runs using dotnet test, I have this workaround in Argu https://github.com/fsprojects/Argu/blob/4c353d9871d318d2459b518ca3dc56cb8c89b112/build.fsx#L102-L113

**Comment by AviAvni** [comment]
@eiriktsarpalis I replaced xunit with Expecto

**Comment by eiriktsarpalis** [comment]
I don't know then. If it doens't work either, the same workaround should apply.

**Comment by AviAvni** [comment]
@eiriktsarpalis  look at the error ```The command "sudo apt-get install -qq mono-complete mono-vbnc fsharp nuget referenceassemblies-pcl" failed and exited with 100 during .``` it dosent get to run the build fail on installing mono

**Comment by eiriktsarpalis** [comment]
I don't think you need to do that, c.f. https://github.com/fsprojects/Argu/blob/4c353d9871d318d2459b518ca3dc56cb8c89b112/.travis.yml#L10

**Comment by AviAvni** [comment]
@eiriktsarpalis  how we can retrigger the build?

**Comment by AviAvni** [comment]
@eiriktsarpalis @forki the build pass on windows and linux
can we merge it and release updated pckage to nuget

**Pull request merged**
