### PR TITLE
Build for netstandard2.0

### PR DESCRIPTION
**Pull request by Jand42**
I have updated Paket and multi-targeting to `net45` and `netstandard2.0`. Tests project still target `net45` only.

The solution builds. I still need some configuration on my side to run tests properly, so I don't have that verified yet, but should work hopefully.

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
Hi, thanks for your PR. You might be interested in [this](https://github.com/fsprojects/FSharp.AWS.DynamoDB/issues/10).

**Comment by AviAvni** [comment]
@Jand42  thanks for you PR can you send it against the dynamodb-local branch
look at https://github.com/fsprojects/FSharp.AWS.DynamoDB/pull/11 the windows build pass linux build I'm checking it

**Comment by Jand42** [comment]
@AviAvni Ok, I will rebase it on dynamodb-local, and I will be able to test it on Windows currently.

**Comment by AviAvni** [comment]
@Jand42  thanks can you check if you need to change something I also worked on changing tests from xunit to expecto

**Comment by AviAvni** [comment]
@Jand42 thanks for your contribution look at https://github.com/fsprojects/FSharp.AWS.DynamoDB/pull/11

**Comment by Jand42** [comment]
@AviAvni Thank you for your work, sorry for leaving the test merge hanging. I have been using a local build for netcore in a project already successfully, waiting for the official NuGet release.

**Comment by AviAvni** [comment]
@Jand42 I pushed new version to nuget

**Pull request closed without merging**
