### PR TITLE
AsyncSeq implementation for DynamoDB

### PR DESCRIPTION
**Pull request by rtkelly13**
Possible implementation for - https://github.com/fsprojects/FSharp.AWS.DynamoDB/issues/14

I think this is a useful addition, might need some work. Maybe splitting into a separate package, couldn't be done due to AttributeWriter being internal.

Had to bump up FSharp.Core version to support it.

### CODE REVIEW

**Comment by samritchie** [comment]
@rtkelly13 I’m working on pagination at the moment, once that’s done it will make adding a separate package considerably simpler, if that’s the best approach.

I don’t have a good feel for how widespread/popular AsyncSeq is, I’m not opposed to adding to this to the core library if it’s the best/most logical addition, but if everyone uses different reactive or async libraries then going separate may be a better idea.

We’d need tests & some examples in the readme.

**Comment by dsyme** [comment]
If I understand rightly this is the situation. 

1. There is an IAsyncEnumerable in the dotnet libraries these days. That should be the standard abstraction to implement.

2. AsyncSeq should be updated to implement that.

3. It is a great way to provide implementations of that abstraction in application code, but there may be others around that don't induce a dependency, or you could roll your own internally.

**Comment by samritchie** [comment]
@dsyme would you expect the other async methods to be migrated to `Task`/`ValueTask` at the same time, or would you see just `IAsyncEnumerable` just being used in this specific case? I’m a bit wary of shipping `Task`-based and `FSharpAsync`-based methods in the same library.

**Comment by rtkelly13** [comment]
I wasn't even aware of IAsyncEnumerable around the time I was doing this but yes that seems like a very good approach to take. 
I'll see if I can dig out the code I originally pushed this PR for as I think I created a neater wrapper in the end outside of here. I was migrating data from one DynamoDB table to another and needed it 
I think AsyncSeq is a great lib but yes I did bump up against the lack of Task support, this may have changed since.

**Comment by bartelink** [comment]
FYI https://github.com/fsprojects/FSharp.Control.TaskSeq is available now - NOTE `0.3.0` has a bug in the impl of `use`, `use!` and `finally`, so need to use `0.4.0-alpha` or later (`Equinox.DynamoStore` uses this lib with TaskSeq)

**Comment by samritchie** [comment]
I’ll close this PR as we’re more likely to use `TaskSeq` now to accomplish this - will continue tracking in #14

**Pull request closed without merging**
